spring:
  application:
    name: grpc-server
  config:
    activate:
      on-profile: local

grpc:
  server:
    port: 9898
  shutdownGrace: 30

public-api:
  weather:
    service-url: "http://apis.data.go.kr/1360000/NwpModelInfoService/getLdapsUnisAll"
    service-key: "UY3ULlYf7kmwiofcwrdho44OoJBaj6eTDw5gA3NLjoYPS86E2AKAJyErwIRBZstsZhbsxumefRsSHZPfsvNhPg=="
