spring:
  pid:
    file: boot.pid
  application:
    name: basic-api
  banner:
    charset: UTF-8
    location: classpath:/banner.txt
  devtools:
    livereload:
      enabled: true
  config:
    activate:
      on-profile: dev
  datasource:
      hikari:
        book:
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/book?characterEncoding=UTF-8&serverTimezone=UTC
          username: kyo
          password: test!1234
          auto-commit: false
          connection-test-query: SELECT 1
          minimum-idle: 10
          maximum-pool-size: 50
          transaction-isolation: TRANSACTION_READ_UNCOMMITTED
          pool-name: pool-book
        test:
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/test?characterEncoding=UTF-8&serverTimezone=UTC
          username: kyo
          password: test!1234
          auto-commit: false
          connection-test-query: SELECT 1
          minimum-idle: 10
          maximum-pool-size: 50
          transaction-isolation: TRANSACTION_READ_UNCOMMITTED
          pool-name: pool-test
  jpa:
    book:
      database-platform: org.hibernate.dialect.MariaDB105Dialect
      properties:
        hibernate:
          format_sql: true
          hbm2ddl.auto: update
          implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          open-in-view: false
          show-sql: true
    test:
      database-platform: org.hibernate.dialect.MariaDB105Dialect
      properties:
        hibernate:
          format_sql: true
          hbm2ddl.auto: update
          implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          open-in-view: false
          show-sql: true

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  shutdown:
    grace-period: 5000

logging:
  dir: /var/log/${spring.application.name}/

log:
  trace:
    file:
      name: trace
      path: ${logging.dir}
  business:
    file:
      name: business
      path: ${logging.dir}

daemon:
  nick-name: kyo ${spring.config.activate.on-profile}
  root-uri: http://locahost:${server.port}
  grpc-ip: 127.0.0.1
  grpc-port: 9899