server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  shutdown:
    grace-period: 5000

spring:
  pid:
    file: boot.pid
  application:
    name: basic-api
  devtools:
    livereload:
      enabled: true
  config:
    import: classpath:daemon.yml, classpath:missing-on-profile.yml
  profiles:
    include:
      - daemon
    group:
      local: daemon-local
      dev: daemon-dev
      live: daemon-live
  datasource:
      hikari:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:49168/book?characterEncoding=UTF-8&serverTimezone=UTC
        username: kyo
        password: woduf8948!
        auto-commit: false
        connection-test-query: SELECT 1
        minimum-idle: 10
        maximum-pool-size: 50
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
        pool-name: pool-book
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      open-in-view: false
      show-sql: true


logging:
  dir: C:/logs/${spring.application.name}

log:
  trace:
    file:
      name: trace
      path: ${logging.dir}
  business:
    file:
      name: business
      path: ${logging.dir}


---
app.name: local


---
app.name: dev


---
app.name: stage


---
app.name: live


---
### 프로파일 선언 없이 사용하는 상황이 벌어지지 않길 바란다!!
app.name: Oh~ NO~~